<?php

namespace Wahid\ProjetTwigBundle\Repository;

/**
 * UsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUserByAgeInterval($ageMin,$ageMax)
    {
        $qb = $this
            ->createQueryBuilder('u')
            ->where('u.age>=:agemin')
            ->andWhere('u.age<=:agemax')
            ->setParameters(
                array(
                    'agemin'=>$ageMin,
                    'agemax'=>$ageMax));

        return $qb
            ->getQuery()
            ->getResult();
    }

    public function getUserByname($word)
    {
        $qb = $this
            ->createQueryBuilder('u')
            ->where('u.name LIKE :word')
            ->orWhere('u.firstName LIKE :word')
            ->setParameters(
                array(
                    'word'=>$word."%",
                    ));
        return $qb
            ->getQuery()
            ->getResult();
    }
}
