<?php

namespace AppBundle\Repository;

/**
 * PersonneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PersonneRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPersonneByAgeInterval($ageMin,$ageMax)
    {
        $qb = $this
            ->createQueryBuilder('p')
            ->where('p.age>=:agemin')
            ->andWhere('p.age<=:agemax')
            ->setParameters(
                array(
                    'agemin'=>$ageMin,
                    'agemax'=>$ageMax));

        return $qb
            ->getQuery()
            ->getResult();
    }
}
