fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

wahid_handling_user:
    resource: "@WahidHandlingUserBundle/Resources/config/routing.yml"
    prefix:   /user

wahid_projet_twig:
    resource: "@WahidProjetTwigBundle/Resources/config/routing.yml"
    prefix:   /projettwig

wahid_session:
    resource: "@WahidSessionBundle/Resources/config/routing.yml"
    prefix:   /session

wahid_first:
    resource: "@WahidFirstBundle/Resources/config/routing.yml"
    prefix:   /firstproject

app_bundle:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /personne

