wahid_projet_twig_homepage:
    path:     /index
    defaults: { _controller: WahidProjetTwigBundle:Default:index }

wahid_projet_twig_cv:
    path:     /cv
    defaults: { _controller: WahidProjetTwigBundle:Default:cv }

wahid_projet_twig_cvs:
    path:     /cvs
    defaults: { _controller: WahidProjetTwigBundle:Default:cvs }